"""Generate nb_helpers.py from ra2ce_tahoe.ipynb.

The notebook carries a lot of hard-won logic - routing-mode post-processing,
equity weighting, the criticality join keyed on rfid_c, the ArcGIS-safe
exports. Re-typing it here would be a chance to introduce new bugs, so this
lifts the relevant cells verbatim and only swaps the config block for one
pointing at this folder.

Cells taken:
  3  closest_node precision patch
  4  select_nearest_routes / od_table_single_destination /
     join_traffic_to_network / archive_graph_files / accumulate_traffic /
     resolve_routing_mode / origin_population
 55  run_od_analysis
"""
import json, io
from pathlib import Path

HERE = Path(__file__).resolve().parent
NB = HERE.parent / "ra2ce" / "ra2ce_tahoe.ipynb"
OUT = HERE / "nb_helpers.py"
CELLS = [3, 4, 55]

CONFIG = '''"""GENERATED by build_helpers.py - do not edit. Edit the notebook or the builder."""
import os, sys, logging
from pathlib import Path

ROOT_DIR     = Path(__file__).resolve().parent
NETWORK_PATH = ROOT_DIR / "static" / "network"
OUTPUT_PATH  = ROOT_DIR / "output"
NETWORK_SHP  = NETWORK_PATH / "overture_split.shp"

PROJ_DIR = str(Path(sys.prefix) / "Library" / "share" / "proj")
os.environ["PROJ_DATA"] = PROJ_DIR
os.environ["PROJ_LIB"]  = PROJ_DIR
import pyproj
pyproj.datadir.set_data_dir(PROJ_DIR)

ORIGINS_SHP         = "Origins.shp"
DESTINATIONS_SHP    = "Destinations.shp"
ORIGINS_COUNT_FIELD = "POPULATION"
EQUITY_WEIGHT_FIELD = ""

ROUTING_MODE = "nearest"
ROUTING_MODE_BY_ANALYSIS = {
    "tahoe_od_medicalfacilities":  "gravity",
    "tahoe_od_evacuationshelters": "gravity",
}
GRAVITY_BETA = 2.0

import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.cm as cm
from matplotlib.colors import LinearSegmentedColormap
from matplotlib.lines import Line2D
from pyproj import CRS

import ra2ce
from ra2ce.ra2ce_handler import Ra2ceHandler
from ra2ce.network.network_config_data.network_config_data import (
    NetworkSection, NetworkConfigData, OriginsDestinationsSection, HazardSection,
)
from ra2ce.network.network_config_data.enums.source_enum import SourceEnum
from ra2ce.network.network_config_data.enums.aggregate_wl_enum import AggregateWlEnum
from ra2ce.analysis.analysis_config_data.analysis_config_data import (
    AnalysisSectionLosses, AnalysisConfigData,
)
from ra2ce.analysis.analysis_config_data.enums.analysis_losses_enum import AnalysisLossesEnum
from ra2ce.analysis.analysis_config_data.enums.weighing_enum import WeighingEnum
'''


def main():
    nb = json.load(io.open(NB, encoding="utf-8"))
    parts = [CONFIG]
    for i in CELLS:
        src = "".join(nb["cells"][i]["source"])
        parts.append(f"\n\n# {'='*70}\n# notebook cell {i}\n# {'='*70}\n{src}\n")
    io.open(OUT, "w", encoding="utf-8").write("\n".join(parts))
    print(f"wrote {OUT}  ({sum(len(p) for p in parts):,} chars from cells {CELLS})")


if __name__ == "__main__":
    main()
