"""GENERATED by build_helpers.py - do not edit. Edit the notebook or the builder."""
import os, sys, logging
from pathlib import Path

ROOT_DIR     = Path(__file__).resolve().parent
NETWORK_PATH = ROOT_DIR / "static" / "network"
OUTPUT_PATH  = ROOT_DIR / "output"
NETWORK_SHP  = NETWORK_PATH / "overture_split.shp"

PROJ_DIR = str(Path(sys.prefix) / "Library" / "share" / "proj")
os.environ["PROJ_DATA"] = PROJ_DIR
os.environ["PROJ_LIB"]  = PROJ_DIR
import pyproj
pyproj.datadir.set_data_dir(PROJ_DIR)

ORIGINS_SHP         = "Origins.shp"
DESTINATIONS_SHP    = "Destinations.shp"
ORIGINS_COUNT_FIELD = "POPULATION"
EQUITY_WEIGHT_FIELD = ""

ROUTING_MODE = "nearest"
ROUTING_MODE_BY_ANALYSIS = {
    "tahoe_od_medicalfacilities":  "gravity",
    "tahoe_od_evacuationshelters": "gravity",
}
GRAVITY_BETA = 2.0

import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.cm as cm
from matplotlib.colors import LinearSegmentedColormap
from matplotlib.lines import Line2D
from pyproj import CRS

import ra2ce
from ra2ce.ra2ce_handler import Ra2ceHandler
from ra2ce.network.network_config_data.network_config_data import (
    NetworkSection, NetworkConfigData, OriginsDestinationsSection, HazardSection,
)
from ra2ce.network.network_config_data.enums.source_enum import SourceEnum
from ra2ce.network.network_config_data.enums.aggregate_wl_enum import AggregateWlEnum
from ra2ce.analysis.analysis_config_data.analysis_config_data import (
    AnalysisSectionLosses, AnalysisConfigData,
)
from ra2ce.analysis.analysis_config_data.enums.analysis_losses_enum import AnalysisLossesEnum
from ra2ce.analysis.analysis_config_data.enums.weighing_enum import WeighingEnum



# ======================================================================
# notebook cell 3
# ======================================================================
# ============================================================
# RA2CE bug patch: closest_node coordinate rounding
# ============================================================
# RA2CE rounds node coordinates to 7 decimal places when snapping OD points,
# breaking dict lookups in inverse_vertices_dict / inverse_nodes_dict when the
# full-precision keys no longer match (e.g. -120.28550210013262 -> -120.2855021).
# Replacing with a version that preserves full float64 precision fixes the issue.

import ra2ce.network.origins_destinations as _od_mod

def _closest_node_fixed(node: np.ndarray, nodes: np.ndarray) -> np.ndarray:
    deltas = nodes - node
    dist_2 = np.einsum("ij,ij->i", deltas, deltas)
    return nodes[np.where(dist_2 == dist_2.min())[0]][0]

_od_mod.closest_node = _closest_node_fixed
print("Applied closest_node precision patch.")



# ======================================================================
# notebook cell 4
# ======================================================================
# ============================================================
# Helpers: routing mode, and joining traffic onto geometry
# ============================================================
# Three helpers used by every criticality analysis in this notebook.
#
# ------------------------------------------------------------------
# 1. ROUTING MODE - select_nearest_routes / od_table_single_destination
# ------------------------------------------------------------------
# AnalysisLossesEnum.OPTIMAL_ROUTE_ORIGIN_DESTINATION routes every origin
# to EVERY destination (a full cross product - see
# _get_origin_destination_pairs in RA2CE), and TrafficAnalysis then splits
# each origin's population evenly across them:
#     traffic = population / count_destination_nodes
# For the 7 basin exits that means each resident contributes 1/7 of a trip
# to all seven, including exits on the far side of the lake. Origin O_0's
# nearest exit is 6.4 km away and its furthest is 73.8 km; both receive the
# same share. Averaged over the basin it inflates mean trip length from
# 10.7 km to 37.6 km and total person-metres by 3.6x, loading long
# cross-basin corridors that nobody would actually drive.
#
# ROUTING_MODE = "nearest" gives each origin one route - to its closest
# destination - carrying its FULL population, which is what the Part 3
# heading has always described and what criticality for evacuation or
# emergency access means. No re-routing is needed: RA2CE already solved the
# optimal path to every destination, so the shortest of them IS the optimal
# path to the nearest one.
#
# ------------------------------------------------------------------
# 2. join_traffic_to_network
# ------------------------------------------------------------------
# TrafficAnalysis / EquityAnalysis key traffic by consecutive node pairs in
# opt_path, which are origins_destinations_graph node ids. Merging those
# straight onto base_network loses most of the result:
#
#   DIRECTION. opt_path pairs run in travel direction; the network stores
#   digitisation direction, which flips arbitrarily along a corridor. On one
#   10,586-edge run, 3,326 pairs matched (node_A, node_B) and 3,873 matched
#   only the reverse, so a forward-only merge drops the larger half - which
#   is what makes traffic alternate on/off along a single road. RA2CE also
#   emits (a,b) and (b,a) as separate rows, so the two directions have to be
#   summed rather than joined separately.
#
#   MISSING EDGES. Snapping origins and destinations splits edges and adds
#   new ones. Those exist in origins_destinations_graph_edges.gpkg but not
#   in base_network, so ~32% of routed edges have no base_network row at all.
#
#   STALE GRAPH. static/output_graph/ is rewritten by every RA2CE run, so
#   scores from one run joined against another run's graph match almost
#   nothing. The old code exported a near-empty file instead of failing.
#
# The fix: fold u/v onto an undirected key, join to
# origins_destinations_graph_edges.gpkg, then carry the score onto the
# original Overture geometry through rfid (base_network.rfid is the
# simplified edge each complex segment belongs to, exactly what
# complex_to_simple.json records).

def select_nearest_routes(od_gdf, length_col="length"):
    """One route per origin: the shortest, i.e. to its closest destination."""
    _r = od_gdf[od_gdf[length_col].notna()]
    _keep = _r.loc[_r.groupby("origin")[length_col].idxmin()]
    print(f"  nearest-destination routing: {len(_keep):,} routes kept "
          f"of {len(od_gdf):,} ({od_gdf['origin'].nunique():,} origins)")
    return _keep.copy()


def od_table_single_destination(od_table, d_col="d_id"):
    """
    Collapse the destination ids to one label.

    TrafficAnalysisBase divides every origin's population by
    len(unique(od_table[d_id])). In nearest-destination mode each origin has
    exactly one route and must contribute its FULL population to it, so the
    divisor has to be 1.
    """
    _t = od_table.copy()
    _mask = _t[d_col].notna()
    _t.loc[_mask, d_col] = "D_NEAREST"
    return _t


def join_traffic_to_network(traffic_frames, root_dir=None, graph_dir=None,
                            min_match_rate=0.99, on_mismatch="raise"):
    """
    Join TrafficAnalysis / EquityAnalysis scores onto the network geometry.

    Parameters
    ----------
    traffic_frames : dict
        {score_column: dataframe}, each the output of
        .optimal_route_od_link(), carrying u, v and that score column.
        A None value is skipped.
    root_dir : Path, optional
        Analysis root. Defaults to the notebook's ROOT_DIR.
    graph_dir : Path, optional
        Directory holding origins_destinations_graph_edges.gpkg and
        base_network.feather. Defaults to <root>/static/output_graph. Point
        this at an archived copy to recompute criticality for an older run
        without re-routing it.
    min_match_rate : float
        Fraction of routed edges that must exist in the graph before the
        result is trusted. Below this, scores and graph are from different runs.
    on_mismatch : {"raise", "warn"}

    Returns
    -------
    (net_scored, scored_edges, info)
    """
    from pathlib import Path
    import geopandas as gpd
    import pandas as pd
    import numpy as np

    _root = Path(root_dir) if root_dir is not None else ROOT_DIR
    _og = Path(graph_dir) if graph_dir is not None else _root / "static" / "output_graph"

    import ast as _ast

    def _undirected_key(u_vals, v_vals):
        return [tuple(sorted((int(a), int(b)))) for a, b in zip(u_vals, v_vals)]

    def _rfid_c_list(v):
        """The complex segment ids a graph edge covers (scalar or list-string)."""
        if isinstance(v, (list, tuple)):
            return [int(x) for x in v]
        if isinstance(v, str) and v.strip().startswith("["):
            return [int(x) for x in _ast.literal_eval(v)]
        try:
            return [int(v)]
        except (TypeError, ValueError):
            return []

    edges = gpd.read_file(_og / "origins_destinations_graph_edges.gpkg")
    edges["_k"] = _undirected_key(edges["u"], edges["v"])
    edge_keys = set(edges["_k"])

    # PARALLEL EDGES. opt_path is a list of NODES, so a route through a
    # multigraph tells us the node pair but not which of several parallel
    # edges was used. Folding on (u,v) therefore hands every parallel edge the
    # same traffic - a little loop beside a direct link reads exactly what the
    # link carries. Example: nodes 56219-56222 carry a 25 m direct edge
    # (key 0) and a 47 m three-segment loop (key 1); the loop was inheriting
    # the direct link's 6,780.
    #
    # Dijkstra on a MultiGraph uses the minimum-weight parallel edge, and the
    # analysis weighed on length, so only the shortest edge of each group can
    # be the one a route actually traversed. Ties are broken deterministically
    # (fewest constituent segments, then lowest rfid) rather than loading both.
    _grp = edges.groupby("_k")["length"]
    edges["_n_par"] = _grp.transform("size")
    edges["_min_len"] = _grp.transform("min")
    edges["_n_seg"] = [len(_rfid_c_list(v)) for v in edges["rfid_c"]]
    _tie = edges["length"] <= edges["_min_len"] + 1e-9
    edges["_rank"] = list(zip(~_tie, edges["_n_seg"], edges["rfid"]))
    edges["_carrier"] = edges.groupby("_k")["_rank"].transform("min") == edges["_rank"]
    _n_alt = int((~edges["_carrier"]).sum())
    if _n_alt:
        print(f"  {_n_alt:,} parallel alternative edges will not receive routed "
              f"traffic (only the shortest edge of each node pair can be on a route)")

    info = {}
    scored_edges = edges.copy()
    score_cols = []

    for col, tdf in traffic_frames.items():
        if tdf is None or col not in getattr(tdf, "columns", []):
            continue
        t = tdf[["u", "v", col]].copy()
        t["_k"] = _undirected_key(t["u"], t["v"])
        # (a,b) and (b,a) are the same physical link, so sum them.
        t = t.groupby("_k", as_index=False)[col].sum()

        rate = float(t["_k"].isin(edge_keys).mean()) if len(t) else 0.0
        info[col] = {"routed_edges": len(t), "match_rate": rate}
        if rate < min_match_rate:
            msg = (
                f"only {rate:.1%} of the {len(t):,} routed edges in '{col}' exist in "
                f"{_og}/origins_destinations_graph_edges.gpkg. static/output_graph/ is "
                f"rewritten by every RA2CE run, so these scores almost certainly belong "
                f"to a different run. Re-run the OD analysis, or pass graph_dir pointing "
                f"at the archived graph for this run."
            )
            if on_mismatch == "raise":
                raise ValueError(msg)
            print(f"  *** WARNING: {msg}")

        scored_edges = scored_edges.merge(t, on="_k", how="left")
        # a parallel alternative was never traversed, so it carries nothing
        scored_edges.loc[~scored_edges["_carrier"], col] = np.nan
        score_cols.append(col)

    if not score_cols:
        raise ValueError("No usable score frames were passed to join_traffic_to_network.")

    # Carry the score onto the original Overture segments.
    #
    # The key is rfid_c, NOT rfid. Every graph edge carries an explicit list of
    # the complex segment ids it covers (e.g. rfid_c = [32184, 8262]), and that
    # list is authoritative: it names exactly which Overture segments make up
    # the simplified edge.
    #
    # base_network.rfid cannot be used for this. It is assigned during the base
    # simplification, before origins and destinations are snapped in; that step
    # splits edges and renumbers them, so 236 rfid values in base_network have
    # no counterpart in the OD graph. Joining on rfid silently dropped 218-245
    # segments per analysis that a *traversed* graph edge explicitly named -
    # they came out as 0 in the middle of loaded corridors.
    #
    # A segment can be named by more than one graph edge (1,610 of them are,
    # up to 6 edges), so take the max rather than summing.
    base_net = gpd.read_feather(_og / "base_network.feather")
    _pairs = [(c, ei) for ei, v in zip(scored_edges.index, scored_edges["rfid_c"])
              for c in _rfid_c_list(v)]
    _map = pd.DataFrame(_pairs, columns=["rfid_c", "_ei"])
    _scores = _map.merge(scored_edges[score_cols], left_on="_ei", right_index=True)
    per_seg = _scores.dropna(subset=score_cols, how="all").groupby("rfid_c")[score_cols].max()

    _named = set(_map["rfid_c"])
    _missing = int((~base_net["rfid_c"].isin(_named)).sum())
    if _missing:
        print(f"  WARNING: {_missing:,} base_network segments are named by no graph "
              f"edge and cannot be scored")

    net_scored = base_net.copy()
    for col in score_cols:
        net_scored[col] = net_scored["rfid_c"].map(per_seg[col])

    # QA flag: segments that sit on a parallel alternative rather than on the
    # edge a route could have used. They are legitimately zero, but the flag
    # distinguishes "alternative link" from "simply not on any route".
    _alt_segs = set()
    for v, carrier in zip(scored_edges["rfid_c"], scored_edges["_carrier"]):
        if not carrier:
            _alt_segs.update(_rfid_c_list(v))
    _carrier_segs = set()
    for v, carrier in zip(scored_edges["rfid_c"], scored_edges["_carrier"]):
        if carrier:
            _carrier_segs.update(_rfid_c_list(v))
    net_scored["par_alt"] = net_scored["rfid_c"].isin(_alt_segs - _carrier_segs).astype(int)
    info["parallel_alt_segments"] = int(net_scored["par_alt"].sum())
    if info["parallel_alt_segments"]:
        print(f"  flagged par_alt=1 on {info['parallel_alt_segments']:,} segments "
              f"({net_scored.loc[net_scored['par_alt'] == 1, 'length'].sum():,.0f} m) "
              f"that lie only on parallel alternatives")

    # A segment no optimal route traverses carries zero population. That is a
    # measured value, not a missing one - "routed" keeps the distinction so
    # maps can grey out untravelled links.
    net_scored["routed"] = net_scored[score_cols].notna().any(axis=1)
    net_scored[score_cols] = net_scored[score_cols].fillna(0.0)
    scored_edges["routed"] = scored_edges[score_cols].notna().any(axis=1)
    scored_edges[score_cols] = scored_edges[score_cols].fillna(0.0)

    info["segments_routed"] = int(net_scored["routed"].sum())
    info["segments_total"] = len(net_scored)
    info["score_columns"] = score_cols

    for col in score_cols:
        _zero = int((net_scored["routed"] & (net_scored[col] == 0)).sum())
        print(f"  {col:22s}: {info[col]['routed_edges']:,} routed graph edges, "
              f"{info[col]['match_rate']:.1%} matched, {_zero:,} routed segments score 0")
    print(f"  {info['segments_routed']:,} of {info['segments_total']:,} network "
          f"segments carry routed traffic; the rest are set to 0")

    return net_scored, scored_edges, info


def archive_graph_files(dest_dir, root_dir=None):
    """
    Copy the two graph files criticality needs next to an analysis' output.

    static/output_graph/ is rebuilt by the next run, which is what makes an
    old analysis impossible to re-score without re-routing it. With these
    archived, join_traffic_to_network(graph_dir=...) can rebuild the
    criticality layers from the saved routes in seconds.
    """
    import shutil
    from pathlib import Path
    _root = Path(root_dir) if root_dir is not None else ROOT_DIR
    _src = _root / "static" / "output_graph"
    _dst = Path(dest_dir); _dst.mkdir(parents=True, exist_ok=True)
    for _name in ("origins_destinations_graph_edges.gpkg", "base_network.feather",
              "origin_destination_table.feather"):
        shutil.copy2(_src / _name, _dst / _name)
    print(f"  archived graph -> {_dst}")
    return _dst


# ------------------------------------------------------------------
# 3. accumulate_traffic - how an origin's population is split across
#    the destinations it was routed to
# ------------------------------------------------------------------
# RA2CE's TrafficAnalysis always divides an origin's population evenly by
# the destination count, which is only meaningful when every destination is
# equally plausible. Three modes are supported here instead:
#
#   "nearest" -- all of an origin's population on its single shortest route.
#                Right where the choice is forced: leaving the basin by the
#                closest exit, or the police station whose jurisdiction you
#                are in. Both of those have few near-ties (median 2nd-best
#                is 1.77x and 1.87x the nearest).
#
#   "gravity" -- population split across destinations in proportion to
#                1 / distance**beta, renormalised to 1. Needed where several
#                facilities are effectively co-located and "nearest" becomes
#                a coin flip: Barton Memorial and Tahoe Urgent Care are 600 m
#                apart, the two Incline Village medical facilities 1.2 km,
#                and 47% of origins have their 2nd-nearest medical facility
#                within 10% of the nearest. Winner-take-all hands one of each
#                pair the whole catchment and leaves the other's access roads
#                reading as unused. Gravity gives both a share, and distant
#                facilities a negligible one.
#
#   "all"      -- RA2CE's own behaviour, population split evenly regardless
#                of distance. Kept for comparison; it loads 70 km hauls as
#                heavily as the corridor next door.
#
# beta is the decay exponent (GRAVITY_BETA, default 2.0). The mode is a
# continuum: beta = 0 reproduces "all", and beta -> infinity reproduces
# "nearest", which is what makes the three comparable.
#
# Returns the same columns RA2CE's optimal_route_od_link() does, so
# join_traffic_to_network consumes it unchanged.

def accumulate_traffic(routes, population, mode="nearest", beta=None,
                       origin_weights=None, length_col="length",
                       origin_col="origin", min_distance=1.0):
    """
    Split each origin's population across its routes and sum onto edges.

    Parameters
    ----------
    routes : GeoDataFrame
        OD routes, with origin, opt_path and a length column. Every
        origin-destination pair, not a pre-filtered subset.
    population : dict or Series
        o_id -> population.
    mode : {"nearest", "gravity", "all"}
    beta : float, optional
        Gravity decay exponent. Defaults to GRAVITY_BETA.
    origin_weights : dict, optional
        o_id -> equity weight, for the prioritarian column. Absent means 1.0,
        which makes traffic_prioritarian equal to traffic.
    min_distance : float
        Floor on route length, so a destination sitting on top of an origin
        cannot produce a divide-by-zero.

    Returns
    -------
    DataFrame [u, v, traffic, traffic_egalitarian, traffic_prioritarian]
    """
    import ast
    from collections import defaultdict
    import numpy as np
    import pandas as pd

    _beta = float(beta if beta is not None else globals().get("GRAVITY_BETA", 2.0))
    if mode not in ("nearest", "gravity", "all"):
        raise ValueError(f"mode must be nearest/gravity/all, got {mode!r}")

    _pop = dict(population) if not isinstance(population, dict) else population
    _w = origin_weights or {}

    util = defaultdict(float)
    egal = defaultdict(float)
    prio = defaultdict(float)

    n_routes = n_origins = 0
    for o_id, grp in routes.groupby(origin_col, sort=False):
        pop = _pop.get(o_id)
        if pop is None or not np.isfinite(pop):
            continue
        d = np.asarray(grp[length_col], dtype="float64")
        d = np.clip(d, min_distance, None)

        if mode == "nearest":
            share = np.zeros(len(d)); share[int(np.argmin(d))] = 1.0
        elif mode == "all":
            share = np.full(len(d), 1.0 / len(d))
        else:
            inv = d ** (-_beta)
            tot = inv.sum()
            share = inv / tot if tot > 0 else np.full(len(d), 1.0 / len(d))

        wt = float(_w.get(o_id, 1.0))
        n_origins += 1
        for s, path in zip(share, grp["opt_path"]):
            if s <= 0:
                continue
            n_routes += 1
            p = ast.literal_eval(path) if isinstance(path, str) else path
            for a, b in zip(p[:-1], p[1:]):
                k = (str(a), str(b))
                util[k] += s * pop
                egal[k] += s
                prio[k] += s * pop * wt

    out = pd.DataFrame(
        [(u, v, util[(u, v)], egal[(u, v)], prio[(u, v)]) for (u, v) in util],
        columns=["u", "v", "traffic", "traffic_egalitarian", "traffic_prioritarian"],
    )
    print(f"  mode={mode}" + (f" beta={_beta:g}" if mode == "gravity" else "")
          + f": {n_origins:,} origins over {n_routes:,} weighted routes "
            f"-> {len(out):,} directed edges")
    return out


def resolve_routing_mode(analysis_name):
    """Per-analysis routing mode, falling back to the global ROUTING_MODE."""
    return ROUTING_MODE_BY_ANALYSIS.get(analysis_name, ROUTING_MODE)


def origin_population(origins_shp, count_field=None):
    """
    Rebuild the o_id -> population lookup RA2CE writes to
    origin_destination_table.feather.

    RA2CE assigns o_id by row order when it reads the origins file, so
    O_<i> is row i. Verified against the feather for all 2,201 origins.
    Lets an archived run be re-scored after static/output_graph/ has moved on.
    """
    import geopandas as gpd
    _f = count_field or ORIGINS_COUNT_FIELD
    g = gpd.read_file(origins_shp).reset_index(drop=True)
    return {f"O_{i}": float(v) for i, v in enumerate(g[_f].fillna(0))}




# ======================================================================
# notebook cell 55
# ======================================================================
# ============================================================
# OD Analysis Function
# ============================================================
# Wraps the OD analysis workflow into a reusable function.
# Accepts custom origin and destination feature class paths.
# Handles both shapefiles and GDB layers automatically.
#
# Usage:
#   run_od_analysis(
#       origins_fc_path="path/to/origins.shp",
#       destinations_fc_path="F:/data.gdb/LayerName",
#       analysis_name="my_od_analysis",
#       origin_count_field="POPULATION",
#   )

def run_od_analysis(
    origins_fc_path,
    destinations_fc_path,
    analysis_name="od_analysis",
    origin_count_field="POPULATION",
    equity_weight_field="",
    reuse_network_output=False,
    network_shapefile=None,
    run_criticality=True,
    equity_regions_shp=None,
    equity_weights_csv=None,
    routing_mode=None,
):
    """
    Execute OD analysis on custom origin/destination feature classes.
    
    Parameters
    ----------
    origins_fc_path : str or Path
        Path to origins feature class (shapefile or GDB layer).
        Formats: "/path/to/file.shp" or "/path/to/file.gdb/LayerName"
    destinations_fc_path : str or Path
        Path to destinations feature class (shapefile or GDB layer).
        Formats: "/path/to/file.shp" or "/path/to/file.gdb/LayerName"
    analysis_name : str
        Name for this analysis (used in output naming).
    origin_count_field : str
        Column name in origins layer containing population/count values.
        Default: "POPULATION".
    equity_weight_field : str
        Optional column name for per-origin equity weighting.
        If blank, only utilitarian analysis is run.
    reuse_network_output : bool
        If True, RA2CE reuses whatever is already in static/output_graph/ and
        IGNORES network_shapefile / primary_file entirely. It also skips
        rebuilding the origins-destinations graph, so a second call with
        different destinations would silently re-use the first call's OD graph.
        Leave this False unless the graph files are known to belong to this
        exact origins/destinations/network combination. Default: False.
    network_shapefile : Path or str, optional
        Path to network shapefile. If None, uses NETWORK_SHP from config.
    run_criticality : bool
        If True, also compute utilitarian and prioritarian (equity-weighted)
        link criticality for this destination set and export the scored
        network. Default: True.
    equity_regions_shp : Path or str, optional
        Region polygons carrying a region-name column, used to assign each
        origin to a region. Defaults to NETWORK_PATH / "blockgroup.shp".
    equity_weights_csv : Path or str, optional
        CSV with "region" and "weight" columns. Defaults to
        NETWORK_PATH / "blockgroup_weights.csv".
    routing_mode : {"nearest", "gravity", "all"}, optional
        How to split each origin's population across destinations. Defaults
        to ROUTING_MODE_BY_ANALYSIS[analysis_name], then ROUTING_MODE.
    
    Returns
    -------
    dict
        Results dictionary with keys:
        - "od_gdf": GeoDataFrame of routes
        - "od_table": OD table with population
        - "base_net": Base network with traffic scores
        - "config": Analysis configuration used
        - "exports": Paths to the written .gpkg / .shp, plus the columns
          dropped from the shapefile for exceeding the .dbf text limit
        - "net_scored": Base network with "traffic" (utilitarian) and
          "traffic_prioritarian" (equity-weighted) columns, or None if
          run_criticality was False or the inputs were unavailable
        - "criticality": Summary stats and export paths for the scored
          network, or None

    Side effects
    ------------
    Writes {analysis_name}_routes.gpkg and {analysis_name}_routes.shp next
    to RA2CE's own output, in output/optimal_route_origin_destination/.
    """
    from pathlib import Path
    import numpy as np
    import geopandas as gpd
    import pandas as pd
    from ra2ce.ra2ce_handler import Ra2ceHandler
    from ra2ce.network.network_config_data.network_config_data import (
        NetworkSection, NetworkConfigData, OriginsDestinationsSection,
    )
    from ra2ce.network.network_config_data.enums.source_enum import SourceEnum
    from ra2ce.analysis.analysis_config_data.analysis_config_data import (
        AnalysisSectionLosses, AnalysisConfigData,
    )
    from ra2ce.analysis.analysis_config_data.enums.analysis_losses_enum import AnalysisLossesEnum
    from ra2ce.analysis.analysis_config_data.enums.weighing_enum import WeighingEnum
    from ra2ce.analysis.losses.traffic_analysis.traffic_analysis import TrafficAnalysis
    from ra2ce.analysis.losses.traffic_analysis.equity_analysis import EquityAnalysis
    from pyproj import CRS
    
    def _read_geospatial_source(source_path):
        """
        Read feature class from shapefile or GDB layer.
        Handles both formats:
          - "/path/file.shp" -> shapefile
          - "/path/file.gdb/LayerName" -> GDB layer
        """
        source_str = str(source_path)
        if ".gdb" in source_str.lower():
            # GDB format: split on .gdb/
            parts = source_str.lower().split(".gdb")
            gdb_path = source_str[:len(parts[0]) + 4]  # Include .gdb
            layer_name = source_str[len(gdb_path)+1:]  # Everything after .gdb/
            print(f"  Reading from GDB: {gdb_path}")
            print(f"  Layer: {layer_name}")
            return gpd.read_file(gdb_path, layer=layer_name)
        else:
            # Shapefile or other format
            print(f"  Reading from: {source_path}")
            return gpd.read_file(source_path)
    
    # Resolve paths
    origins_path = Path(origins_fc_path)
    destinations_path = Path(destinations_fc_path)
    net_shp = Path(network_shapefile) if network_shapefile else NETWORK_SHP
    
    print(f"\n{'='*60}")
    print(f"Running OD Analysis: {analysis_name}")
    print(f"{'='*60}")
    print(f"Origins:      {origins_path}")
    print(f"Destinations: {destinations_path}")
    print(f"Network:      {net_shp}")
    print(f"{'='*60}\n")
    
    # Read origins and destinations using smart loader
    print("Loading origins...")
    origins_gdf = _read_geospatial_source(origins_path)
    print(f"  {len(origins_gdf):,} features | CRS: {origins_gdf.crs}")
    
    print("Loading destinations...")
    dests_gdf = _read_geospatial_source(destinations_path)
    print(f"  {len(dests_gdf):,} features | CRS: {dests_gdf.crs}")
    
    # Ensure both are in EPSG:4326
    if origins_gdf.crs is None or origins_gdf.crs.to_epsg() != 4326:
        print("  Reprojecting origins to EPSG:4326...")
        origins_gdf = origins_gdf.to_crs(4326)
    if dests_gdf.crs is None or dests_gdf.crs.to_epsg() != 4326:
        print("  Reprojecting destinations to EPSG:4326...")
        dests_gdf = dests_gdf.to_crs(4326)
    
    # Keep only Point geometries for destinations
    dests_gdf = dests_gdf[dests_gdf.geometry.geom_type == "Point"].copy().reset_index(drop=True)
    print(f"  Point features kept: {len(dests_gdf):,}")

    # ============================================================
    # Materialize the prepared OD inputs as shapefiles
    # ============================================================
    # RA2CE opens the origins/destinations paths itself, with a plain
    # gpd.read_file(path). That cannot open a File GDB feature class -
    # "<db>.gdb\LayerName" is not a path GDAL recognises, so passing the
    # GDB path straight through raises
    #   DataSourceError: ...gdb\LocalLawEnforcement: No such file or directory
    # even though _read_geospatial_source above read it fine.
    #
    # Writing the already-prepared GeoDataFrames out and pointing RA2CE at
    # those shapefiles fixes that, and also means the EPSG:4326
    # reprojection and the Point-only filter above actually reach RA2CE
    # instead of being discarded.
    if origin_count_field and origin_count_field not in origins_gdf.columns:
        print(f"  Warning: '{origin_count_field}' not in origins; adding it as 1 per origin")
        origins_gdf[origin_count_field] = 1

    od_origins_shp = NETWORK_PATH / f"{analysis_name}_origins.shp"
    od_dests_shp   = NETWORK_PATH / f"{analysis_name}_destinations.shp"
    origins_gdf.to_file(od_origins_shp)
    dests_gdf.to_file(od_dests_shp)
    print(f"  Prepared origins      -> {od_origins_shp.name}")
    print(f"  Prepared destinations -> {od_dests_shp.name}")

    # A shapefile .dbf truncates field names to 10 characters, which would
    # silently break the origin_count lookup inside RA2CE.
    if origin_count_field:
        written = gpd.read_file(od_origins_shp, rows=1)
        if origin_count_field not in written.columns:
            raise ValueError(
                f"origin_count field '{origin_count_field}' did not survive the "
                f"shapefile write (10-char .dbf limit). Rename it to <=10 chars "
                f"in the source layer. Written columns: {list(written.columns)}"
            )

    
    # Configure network
    #
    # reuse_network_output=True makes NetworkConfigWrapper load the existing
    # static/output_graph/ and never look at primary_file:
    #     if reuse_network_output:  graph_files = read_graphs_from_config(dir)
    #     else:                     shutil.rmtree(dir)
    # and Network.create() then skips the OD graph too, because
    #     if origins and destinations and not origins_destinations_graph.file
    # is already satisfied. So reusing here silently routes on whichever
    # network and destination set happened to be built last. Default False.
    network_section = NetworkSection(
        source=SourceEnum.SHAPEFILE,
        primary_file=net_shp,
        save_gpkg=True,
        reuse_network_output=reuse_network_output,
    )
    print(f"Network graph: {'REUSING static/output_graph' if reuse_network_output else 'rebuilding from ' + net_shp.name}")
    
    # Configure OD section
    od_section = OriginsDestinationsSection(
        origins=od_origins_shp,
        destinations=od_dests_shp,
        origin_count=origin_count_field,
    )
    
    # Build network config
    network_config = NetworkConfigData(
        root_path=ROOT_DIR,
        static_path=ROOT_DIR / "static",
        crs=CRS.from_epsg(4326),
        network=network_section,
        origins_destinations=od_section,
    )
    
    # Configure analysis
    od_analysis_config = AnalysisSectionLosses(
        name=analysis_name,
        analysis=AnalysisLossesEnum.OPTIMAL_ROUTE_ORIGIN_DESTINATION,
        weighing=WeighingEnum.LENGTH,
        calculate_route_without_disruption=True,
        save_csv=True,
        save_gpkg=True,
    )
    
    analysis_config = AnalysisConfigData(
        output_path=OUTPUT_PATH,
        static_path=ROOT_DIR / "static",
        analyses=[od_analysis_config],
    )
    
    # Run RA2CE
    print("Configuring RA2CE handler...")
    handler = Ra2ceHandler.from_config(network=network_config, analysis=analysis_config)
    handler.configure()
    print("Running analysis...")
    handler.run_analysis()
    
    # Load results
    print("\nLoading results...")
    od_gpkg_path = OUTPUT_PATH / "optimal_route_origin_destination" / f"{analysis_name}.gpkg"
    if not od_gpkg_path.exists():
        raise FileNotFoundError(f"Expected output not found: {od_gpkg_path}")
    
    od_gdf_result = gpd.read_file(od_gpkg_path)
    print(f"OD routes: {len(od_gdf_result):,}")

    # ============================================================
    # Export routes for ArcGIS Pro (GeoPackage + Shapefile)
    # ============================================================
    # RA2CE writes its own .gpkg above, but it carries list-typed columns
    # and an empty-named column that breaks ArcGIS Pro's SQL tokenizer.
    # These exports are re-typed to plain scalars.
    #
    # opt_path / match_ids are node and edge id lists up to ~4,000
    # characters long. A .dbf caps text at 254 and truncates silently,
    # leaving a half-written list that still looks like a valid value, so
    # over-long columns are dropped from the shapefile and kept in full in
    # the GeoPackage.
    export_dir = od_gpkg_path.parent
    DBF_TEXT_LIMIT = 254

    def _to_str(v):
        if v is None:
            return ""
        try:
            if isinstance(v, float) and np.isnan(v):
                return ""
        except (TypeError, ValueError):
            pass
        if isinstance(v, (list, tuple, np.ndarray)):
            return "|".join(str(x) for x in v)
        if isinstance(v, bytes):
            return v.decode("utf-8", errors="replace")
        return str(v)

    od_clean = od_gdf_result.copy()
    for col in od_clean.columns:
        if col == od_clean.geometry.name:
            continue
        s = od_clean[col]
        if s.dtype.kind == "f":
            od_clean[col] = s.astype("float64")
        elif s.dtype.kind in ("i", "u"):
            od_clean[col] = s.astype("int64")
        else:
            od_clean[col] = s.apply(_to_str)

    print("\nExporting routes...")
    out_gpkg = export_dir / f"{analysis_name}_routes.gpkg"
    out_gpkg.unlink(missing_ok=True)
    od_clean.to_file(out_gpkg, driver="GPKG", layer=f"{analysis_name}_routes")
    print(f"  GeoPackage: {out_gpkg.resolve()}")

    too_long = [
        c for c in od_clean.columns
        if c != od_clean.geometry.name
        and od_clean[c].dtype.kind == "O"
        and od_clean[c].str.len().max() > DBF_TEXT_LIMIT
    ]
    od_shp_ready = od_clean.drop(columns=too_long)
    if too_long:
        print(f"  Dropped from shapefile (over the {DBF_TEXT_LIMIT}-char .dbf limit): "
              f"{', '.join(too_long)} -- kept in full in the GeoPackage")

    out_shp = export_dir / f"{analysis_name}_routes.shp"
    od_shp_ready.to_file(out_shp)
    print(f"  Shapefile:  {out_shp.resolve()}")
    print("  (field names over 10 chars are truncated in the .dbf, "
          "e.g. destination -> destinatio)")
    
    # Load OD table if available
    od_table_path = ROOT_DIR / "static" / "output_graph" / "origin_destination_table.feather"
    if od_table_path.exists():
        od_table = pd.read_feather(od_table_path)
        print(f"OD table: {len(od_table):,} rows")
    else:
        od_table = None
        print("Warning: OD table feather not found")
    
    # Load base network if available
    base_net_path = ROOT_DIR / "static" / "output_graph" / "base_network.feather"
    if base_net_path.exists():
        base_net = gpd.read_feather(base_net_path)
        print(f"Base network: {len(base_net):,} edges")
    else:
        base_net = None
        print("Warning: Base network feather not found")

    # ============================================================
    # Link criticality: utilitarian + prioritarian (equity-weighted)
    # ============================================================
    # Utilitarian  -- segment score = sum of (origin population / n dests)
    #                 over every origin whose optimal route uses it.
    # Prioritarian -- the same, with each origin's population multiplied by
    #                 its region's equity weight (0-1), so links serving
    #                 higher-need areas rank higher.
    #
    # Both run on the origin-level OD table. Each origin is tagged with the
    # region it falls in and EquityAnalysis applies that region's weight
    # row-wise; see the note above the EquityAnalysis call for why the table
    # must not be aggregated to one row per region.
    net_scored = None
    criticality = None

    if not run_criticality:
        print("\nSkipping criticality (run_criticality=False)")
    elif od_table is None or base_net is None:
        print("\nSkipping criticality: OD table or base network unavailable")
    elif not {"origin", "opt_path"}.issubset(od_gdf_result.columns):
        print("\nSkipping criticality: routes lack 'origin'/'opt_path' columns")
    else:
        regions_shp = Path(equity_regions_shp) if equity_regions_shp else NETWORK_PATH / "blockgroup.shp"
        weights_csv = Path(equity_weights_csv) if equity_weights_csv else NETWORK_PATH / "blockgroup_weights.csv"

        print(f"\n{'-'*60}")
        print("Link criticality")
        print(f"{'-'*60}")

        # -- utilitarian ------------------------------------------------
        # TrafficAnalysis hardcodes "values" as the population column.
        od_table_ta = od_table.rename(columns={origin_count_field: "values"})
        total_pop = float(od_table_ta["values"].sum())
        _pop_by_origin = od_table.set_index("o_id")[origin_count_field].to_dict()
        _mode = routing_mode or resolve_routing_mode(analysis_name)
        print(f"Routing mode: {_mode}")
        traffic_df = accumulate_traffic(od_gdf_result, population=_pop_by_origin,
                                        mode=_mode)
        print(f"Utilitarian : {len(traffic_df):,} edges, "
              f"range {traffic_df['traffic'].min():.2f} -- {traffic_df['traffic'].max():.2f} "
              f"(total population {total_pop:,.0f})")

        # -- prioritarian ------------------------------------------------
        traffic_eq_df = None
        if not (regions_shp.exists() and weights_csv.exists()):
            print(f"Prioritarian: skipped -- missing {regions_shp.name} "
                  f"and/or {weights_csv.name}")
        else:
            equity_data = pd.read_csv(weights_csv)
            regions_gdf = gpd.read_file(regions_shp)
            region_col = next(
                (c for c in regions_gdf.columns
                 if "region" in c.lower() and c != regions_gdf.geometry.name),
                None,
            )
            if region_col is None:
                print(f"Prioritarian: skipped -- no region-name column in {regions_shp.name}")
            else:
                # Map each origin to a region. Read the *prepared* origins
                # file, not the source layer, so the positional index lines
                # up with the O_<i> ids RA2CE assigned when it read them.
                prepared_origins = gpd.read_file(od_origins_shp)
                if prepared_origins.crs != regions_gdf.crs:
                    regions_gdf = regions_gdf.to_crs(prepared_origins.crs)

                sj = gpd.sjoin(
                    prepared_origins[[prepared_origins.geometry.name]],
                    regions_gdf[[region_col, regions_gdf.geometry.name]],
                    how="left", predicate="within",
                )
                # An origin on a shared region boundary can match twice;
                # keep the first so the o_id -> region map stays 1:1.
                sj = sj[~sj.index.duplicated(keep="first")]
                o_id_to_region = {
                    f"O_{i}": str(r) for i, r in sj[region_col].items() if pd.notna(r)
                }
                print(f"Origins mapped to regions: {len(o_id_to_region):,} / "
                      f"{len(prepared_origins):,}")

                od_eq = od_table_ta.copy()
                od_eq["region"] = od_eq["o_id"].map(o_id_to_region)
                matched = od_eq["region"].notna().sum()
                if matched == 0:
                    print("Prioritarian: skipped -- no OD rows matched a region "
                          f"(o_id samples: {list(od_eq['o_id'].head(3))})")
                else:
                    print(f"OD rows with a region: {matched:,} / {len(od_eq):,}")

                    # The table stays at ORIGIN level. EquityAnalysis looks each
                    # route's origin up with
                    #     od_table.loc[od_table["o_id"] == origin_node, col].values[0]
                    # where origin_node is the route's "origin" value ("O_0", ...),
                    # and computes values_prioritarian row-wise as
                    #     region -> weight  x  values
                    # So "region" only has to be a *column*; aggregating to one row
                    # per region and setting o_id = region name makes every lookup
                    # miss and raises IndexError on the first origin. The table also
                    # has to keep its "d_id" column, because the base class counts
                    # destinations with od_table["d_id"] before scoring anything.
                    weighted_regions = set(equity_data["region"])
                    od_eq["region"] = od_eq["region"].where(
                        od_eq["region"].isin(weighted_regions), "Not assigned"
                    )
                    n_unassigned = int((od_eq["region"] == "Not assigned").sum())
                    if n_unassigned:
                        print(f"  {n_unassigned:,} of {len(od_eq):,} rows have no "
                              f"region weight -> 'Not assigned', which RA2CE scores "
                              f"at weight 1.0")

                    _wt_by_region = dict(zip(equity_data["region"],
                                             equity_data["weight"]))
                    _origin_wt = {
                        o: float(_wt_by_region.get(r, 1.0))
                        for o, r in zip(od_eq["o_id"], od_eq["region"])
                    }
                    traffic_eq_df = accumulate_traffic(
                        od_gdf_result, population=_pop_by_origin,
                        mode=_mode, origin_weights=_origin_wt,
                    )

                    col = "traffic_prioritarian"
                    n_inf = int(traffic_eq_df[col].isin([np.inf, -np.inf]).sum())
                    if n_inf:
                        print(f"  Replaced {n_inf:,} infinite prioritarian values with 0")
                        traffic_eq_df[col] = traffic_eq_df[col].replace([np.inf, -np.inf], 0)
                    traffic_eq_df[col] = traffic_eq_df[col].fillna(0)
                    print(f"Prioritarian: {int((traffic_eq_df[col] > 0).sum()):,} edges "
                          f"non-zero, range {traffic_eq_df[col].min():.2f} -- "
                          f"{traffic_eq_df[col].max():.2f}")

        # -- join both score sets onto the network geometry ---------------
        # The scores are keyed by origins_destinations_graph node ids, so
        # they go through join_traffic_to_network (Part 1) instead of a
        # direct merge onto base_network. That helper folds the two travel
        # directions together and raises when static/output_graph/ no longer
        # belongs to this run - the old merge could not tell the difference
        # and simply exported a near-empty file.
        print("\nJoining scores to network geometry:")
        net_scored, scored_edges, join_info = join_traffic_to_network(
            {
                "traffic": traffic_df,
                "traffic_egalitarian": traffic_df,
                "traffic_prioritarian": traffic_eq_df,
            },
            root_dir=ROOT_DIR,
        )

        n_util = int((net_scored["traffic"] > 0).sum())
        n_prio = (int((net_scored["traffic_prioritarian"] > 0).sum())
                  if "traffic_prioritarian" in net_scored.columns else 0)
        join_rate = join_info["traffic"]["match_rate"]
        n_routed = join_info["segments_routed"]
        n_unrouted = join_info["segments_total"] - n_routed
        print(f"Segments with traffic: {n_util:,} utilitarian, "
              f"{n_prio:,} prioritarian (of {len(net_scored):,})")

        # static/output_graph/ is rebuilt by the next run, which is what makes
        # an older analysis impossible to re-score without repeating the
        # routing. Keep the two files criticality needs beside its output.
        archive_graph_files(export_dir / f"{analysis_name}_graph", root_dir=ROOT_DIR)

        crit_gpkg = export_dir / f"{analysis_name}_criticality.gpkg"
        crit_shp = export_dir / f"{analysis_name}_criticality.shp"
        crit_out = net_scored.copy()
        for c in crit_out.columns:
            if c == crit_out.geometry.name:
                continue
            s = crit_out[c]
            if s.dtype == bool:
                crit_out[c] = s.astype("int64")
            elif s.dtype.kind == "f":
                crit_out[c] = s.astype("float64")
            elif s.dtype.kind in ("i", "u"):
                crit_out[c] = s.astype("int64")
            else:
                crit_out[c] = s.apply(_to_str)
        # An unnamed column comes through from RA2CE's base_network and
        # is what breaks ArcGIS Pro's SQL parser on the .gpkg.
        crit_out = crit_out.rename(
            columns={c: "unnamed" for c in crit_out.columns if str(c).strip() == ""}
        )
        crit_gpkg.unlink(missing_ok=True)
        crit_out.to_file(crit_gpkg, driver="GPKG", layer=f"{analysis_name}_criticality")
        crit_out.to_file(crit_shp)
        print(f"  GeoPackage: {crit_gpkg.resolve()}")
        print(f"  Shapefile:  {crit_shp.resolve()}")

        criticality = {
            "gpkg": crit_gpkg,
            "shp": crit_shp,
            "edges_utilitarian": n_util,
            "edges_prioritarian": n_prio,
            "scored_edges": join_info["traffic"]["routed_edges"],
            "join_rate": join_rate,
            "edges_with_traffic": n_routed,
            "edges_without_traffic": n_unrouted,
            "total_population": total_pop,
            "regions_shp": regions_shp,
            "weights_csv": weights_csv,
        }
    
    results = {
        "od_gdf": od_gdf_result,
        "od_table": od_table,
        "base_net": base_net,
        "net_scored": net_scored,
        "criticality": criticality,
        "exports": {
            "gpkg": out_gpkg,
            "shp": out_shp,
            "shp_dropped_columns": too_long,
        },
        "config": {
            "analysis_name": analysis_name,
            "origins": str(origins_path),
            "destinations": str(destinations_path),
            "origin_count_field": origin_count_field,
            "prepared_origins": od_origins_shp,
            "prepared_destinations": od_dests_shp,
            "equity_weight_field": equity_weight_field,
        },
    }
    
    print(f"\n{'='*60}")
    print(f"Analysis complete: {analysis_name}")
    print(f"{'='*60}\n")
    
    return results


# ============================================================
# Example Usage - Multiple Destination Analysis
# ============================================================
# Uncomment to run OD analysis for multiple destinations:

# destination_fcs = {
#     "LocalLawEnforcement": "F:/GIS/PROJECTS/Transportation/Protect/PROTECT_analysis/PROTECT_analysis.gdb/LocalLawEnforcement",
#     "HospitalClinic": "F:/GIS/PROJECTS/Transportation/Protect/PROTECT_analysis/PROTECT_analysis.gdb/HospitalClinic",
#     "Airport": "F:/GIS/PROJECTS/Transportation/Protect/PROTECT_analysis/PROTECT_analysis.gdb/Airport",
# }
# origin_featureclass = "F:/GIS/PROJECTS/Transportation/Protect/PROTECT_analysis/PROTECT_analysis.gdb/BlockGroups"
#
# results_dict = {}
# for dest_name, dest_fc in destination_fcs.items():
#     print(f"\nRunning OD analysis for destination: {dest_name}")
#     result = run_od_analysis(
#         origins_fc_path=origin_featureclass,
#         destinations_fc_path=dest_fc,
#         analysis_name=f"tahoe_od_{dest_name}",
#         origin_count_field="POPULATION",
#     )
#     results_dict[dest_name] = result
#     print(f"✓ Completed: {dest_name}")
#
# print(f"\n✓ All analyses complete. Results stored in results_dict")

